### PR TITLE
Make OpenSSLCSRGenerator return a CSR string

### PR DESCRIPTION
**Pull request by prewk**
I added a test which might need some `Amp` cleanup.

I don't know how to trigger the `openssl_csr_new` error so I didn't write a test case for it.

### CODE REVIEW

**Comment by kelunik** [comment]
Thanks! I think we should change the generator to return a promise instead of a generator, given that's what the interface defines.

**Comment by prewk** [comment]
Will you include this is an upcoming larger release or is it possible to get the changes out for a `0.4.1`?

**Comment by kelunik** [comment]
It will definitely be `0.4.1`, as that part is otherwise unusable anyway.

**Comment by kelunik** [comment]
I have just released `v0.4.1`.

**Pull request merged**
