### PR TITLE
Separate verifiers into their own classes

### PR DESCRIPTION
**Pull request by kelunik**
@DSpeichert @kfeutz What do you think?

Any other name suggestions?

### CODE REVIEW

**Comment by DSpeichert** [comment]
Looks like a nice change @kelunik !

I'd suggest using 
```
namespace Kelunik\Acme\Verifiers;
```

so that the classes would be e.g. `Kelunik\Acme\Verifiers\Dns01` or `Kelunik\Acme\Verifiers\Dns01Verifier` but that's just a suggestion.

**Comment by kelunik** [comment]
I don't know whether I should `generateKeyAuthorization` as well, thoughts?

**Comment by kelunik** [comment]
Moved them into their own namespace, `generateKeyAuthorization` still remaining.

**Comment by kelunik** [comment]
Rebase into master.

**Pull request closed without merging**
